league_ids = {
    'Premiership': 6135,
    'Championship': 'england/championship/',
    'League 1': 'england/league-one/',
    'League 2': 'england/league-two/',
    'National League': 'england/national-league/',
    'SCOT': 'scotland/premiership/',
    'La Liga': 'spain/laliga/',
    'Bundesliga': 'germany/bundesliga/',
    'Serie A': 'italy/serie-a/',
    'Ligue 1': 'france/ligue-1/',
    'Eredivisie': 'netherlands/eredivisie/',
    'Champions League': 'uefa/champions-league/',
    'Europa League': 'uefa/europa-league/',
}