league_logos = {
    'Premiership': 'premier-league.png',
    'Championship': 'championship.png',
    'League 1': 'league1.png',
    'League 2': 'league2.png',
    'National League': 'national.png',
    'Scottish Premiership': 'scotprem.png',
    'Scottish Championship': 'scotchamp.png',
    'La Liga': 'laliga.png',
    'Bundesliga': 'bundesliga.png',
    'Serie A': 'seriea.png',
    'Serie B': 'serieb.png',
    'Ligue 1': 'ligue1.png',
    'Eredivisie': 'eredivisie.png',
    'Jupiler Pro League': 'jupiler.png',
    'MLS': 'mls.png',
    'Hungarian NB1': 'nb1.png',
    'Argentina Superliga': 'superliga.png',
    'Champions League': 'championsleague.png',
    'Europa League': 'europaleague.png',
}