league_logos = {
    'premiership': 'premier-league.png',
    'championship': 'championship.png',
    'league 1': 'league1.png',
    'league 2': 'league2.png',
    'national league': 'national.png',
    'scottish premiership': 'scotprem.png',
    'scottish championship': 'scotchamp.png',
    'la liga': 'laliga.png',
    'bundesliga': 'bundesliga.png',
    'serie a': 'seriea.png',
    'serie b': 'serieb.png',
    'ligue 1': 'ligue1.png',
    'eredivisie': 'eredivisie.png',
    'jupiler pro league': 'jupiler.png',
    'mls': 'mls.png',
    'hungarian nb1': 'nb1.png',
    'argentina superliga': 'superliga.png',
    'champions league': 'championsleague.png',
    'europa league': 'europaleague.png',
    'europa conference league': 'europaconferenceleague.png',
    'fa cup': 'facup.png',
}